### PR TITLE
Swap out the release candidate for ICU 67.1 for the official release

### PR DESCRIPTION
**Pull request by datalogics-robb**
Changes in the PR consist only of the yaml file, which will be a new recipe revision.

### CODE REVIEW

**Comment by datalogics-kam** [comment]
Made a `stable/67.1` to be the destination branch, and pointed this PR at it.

**Comment by datalogics-kam** [comment]
I recommend this change so that the export works on Windows.

```diff
diff --git a/.gitattributes b/.gitattributes
index d9bd16b..f157709 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1 +1,3 @@
 *.py text eol=lf
+conandata.yml text eol=lf
+LICENSE.md text eol=lf
```

Basically, `conanfile.py` plus files that are listed when doing `conan export` have to have LF endings.

```
❯ conan export . icu/67.1@kam/testing
Exporting package recipe
icu/67.1@kam/testing exports: File 'conandata.yml' found. Exporting it...
icu/67.1@kam/testing exports: Copied 1 '.yml' file: conandata.yml
icu/67.1@kam/testing exports: Copied 1 '.md' file: LICENSE.md
icu/67.1@kam/testing exports: Copied 1 '.py' file: icu_base.py
```

**Comment by datalogics-robb** [comment]
@datalogics-kam why put `LICENSE.md` in there?
Is that part of the recipe too?

**Comment by datalogics-kam** [comment]
> Is that part of the recipe too?

Yes, it's in the [exports list](https://github.com/datalogics/conan-icu/blob/stable/67.1/icu_base.py#L18) in `icu_base.py`. Some of these OSS projects carry their license info into the recipe.

This project is confusing enough, which is why I suggested using the output of `conan export` as a guide.

**Pull request merged**
