### PR TITLE
APDFL-3200 Add a patch for ICU CVE present in 66.1

### PR DESCRIPTION
**Pull request by datalogics-robb**
APDFL-3200 Add a patch for ICU CVE present in 66.1

### CODE REVIEW

**Comment by datalogics-kam** [comment]
I'm going to check this out on my Mac and review it.

In the meantime, should we put a patch number in the version, like `66.1+dl1`, just to make sure it distinguishes from the official `66.1`?

Conan seems to understand `+b102` for instance: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#versioning-schema
Semver doc: https://semver.org/#spec-item-10

**Comment by datalogics-robb** [comment]
I would agree that we should give it a new version number.
BUT on another note, far as APDFL-3200 is concerned, there is an ICU 67 release candidate out, and we may be better off using that.  I would also like to use the "versions as data" schema that's used in the conan-center-index - so that we don't need a new branch for each version of the package, and IMO it's easier to deal with adding a few lines to a yaml file.

**Comment by datalogics-kam** [comment]
> there is an ICU 67 release candidate out, and we may be better off using that.

I'm assuming that it has the fix we need.

>  I would also like to use the "versions as data" schema that's used in the conan-center-index

Fantastic! I would certainly welcome that. What happens to patches? List of patches in the `conandata.yml`, and then just keep the patches versioned/separate file?

**Comment by datalogics-robb** [comment]
In this case, we'd take out this patch, and there would be none remaining.  If we needed patches for certain versions, I would imagine they could be put in versioned directories, as another entry in the yaml file.

**Comment by datalogics-robb** [comment]
Since I cannot make this PR a work in progress, I'm going to close it.  We've identified that if we were to use ICU 66.1 we would want changes, but we're going to go the route of using ICU 67RC1 instead.

**Comment by datalogics-kam** [comment]
To test this, I built APDFL 18 with it, and ran the DevTests.

I haven't investigated yet, but it causes these two tests to fail where they don't fail on `develop`:

- APDFL_Samples
- SF34777

(yeah, I know it's closed, but at least we have this recorded somewhere)

**Pull request closed without merging**
